{% set name = "lnav" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tstack/{{ name|lower }}/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: e1e70c9e5a2fce21da80eec9b9c3adb09fd05e03986285098a9f2567c1eb4792

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - make
    - pkg-config
    - sed
  host:
    - bzip2
    - jemalloc
    - libarchive
    - libcurl >=7.80.0
    - libunistring
    - ncurses
    - pcre2
    - readline
    - sqlite
    - zlib

test:
  commands:
    - lnav -V
    - printf 'lnav' | lnav -n -c ';from [{ col1=1 }] | take 1' | grep -q col1

about:
  home: https://lnav.org
  dev_url: https://github.com/tstack/lnav
  doc_url: https://docs.lnav.org
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "A log file viewer for the terminal"
  description: |
    The Logfile Navigator is a log file viewer for the terminal. Given a set of files/directories, lnav will:

      - decompress as needed;
      - detect their format;
      - merge the files by time into a single view;
      - tail the files, follow renames, find new files in directories;
      - build an index of errors and warnings;
      - pretty-print JSON-lines.

    Then, in the lnav TUI, you can:

      - jump quickly to the previous/next error (press e/E);
      - search using regular expressions (press /);
      - highlight text with a regular expression (:highlight command);
      - filter messages using regular expressions or SQLite expressions;
      - pretty-print structured text (press P);
      - view a histogram of messages over time (press i);
      - analyze messages using SQLite (press ;)

extra:
  recipe-maintainers:
    - eunos-1128
