context:
  name: lnav
  version: "0.13.0"
  sha256: 1d24b9bdb59e3de995de95f6f029ace664e56a80fb0db945077687e86de586b7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tstack/${{ name }}/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - make
    - pkg-config
    - sed
    - if: build_platform != target_platform
      then: zlib
  host:
    - bzip2
    - jemalloc
    - libarchive
    - libcurl >=7.80.0
    - libunistring
    - ncurses
    - pcre2
    - readline
    - sqlite
    - zlib

tests:
  - script:
      - lnav -V
      - printf 'lnav' | lnav -n -c ';from [{ col1=1 }] | take 1' | grep -q col1

about:
  homepage: https://lnav.org
  repository: https://github.com/tstack/lnav
  documentation: https://docs.lnav.org
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "A log file viewer for the terminal"
  description: |
    The Logfile Navigator is a log file viewer for the terminal. Given a set of files/directories, lnav will:

      - decompress as needed;
      - detect their format;
      - merge the files by time into a single view;
      - tail the files, follow renames, find new files in directories;
      - build an index of errors and warnings;
      - pretty-print JSON-lines.

    Then, in the lnav TUI, you can:

      - jump quickly to the previous/next error (press e/E);
      - search using regular expressions (press /);
      - highlight text with a regular expression (:highlight command);
      - filter messages using regular expressions or SQLite expressions;
      - pretty-print structured text (press P);
      - view a histogram of messages over time (press i);
      - analyze messages using SQLite (press ;)

extra:
  recipe-maintainers:
    - eunos-1128
